use_frameworks!
inhibit_all_warnings!

platform :ios, '14.0'

target 'WhimCore_Example' do
  pod 'WhimCore', :path => '../', :testspecs => ['Tests'], :inhibit_warnings => false
  pod 'WhimUtils', :git => 'https://github.com/maasglobal/whim-ios-utils'

  # Testing
  pod 'WhimRandom', :git => 'https://github.com/maasglobal/whim-ios-random'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
