name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Testing network framework
    runs-on: [self-hosted, macOS, X64]    
    timeout-minutes: 12 
    
    steps:    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          ImageOS: macos1015
        with:
          ruby-version: 2.7
        
      - name: Update cocoapods
        run: |    
          gem install bundler
          bundle install 
      
      - name: Update cocoapods 2
        run: |                    
          cd Example && bundle exec pod install --repo-update

      - name: Running tests
        run: |                    
          set -o pipefail && xcodebuild -workspace WhimNetworkExample/WhimNetworkExample.xcworkspace -scheme WhimNetworkExample -derivedDataPath Build/ -enableCodeCoverage YES -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' build test | xcbeautify

      - name: Format coverage files with slather
        run: |
          bundle exec slather

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
